"""Updated firewall malicious Ip related tables.

Revision ID: 1b46d55146b6
Revises: 8b27db5146b6
Create Date: 2021-04-23 12:25:44.147852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b46d55146b6'
down_revision = '8b27db5146b6'
branch_labels = None
depends_on = None


maliciousIPSourceEnum = sa.Enum('firewall_inbound_traffic', 'firewall_outbound_traffic', 'firewall_ddos_attack', 'honeypot', 'dmz', name='enum_malicious_ip_sources')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("Migrating from initial centralized malicious Ip list to firewall malicious list for new global Radar API.")
    # column renames/drop
    op.drop_column('malicious_ips', 'id')
    op.drop_column('malicious_ips', 'no_of_ports_used')
    op.drop_column('malicious_ips', 'no_of_victims')
    op.alter_column('malicious_ips', 'hits', new_column_name='no_of_hits')
    op.drop_column('affected_device', 'device_name')

    # rename tables
    op.rename_table('maliciousip', 'firewall_maliciousip')
    op.rename_table('affected_device', 'firewall_affected_device')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # column renames/drop downgrade
    op.add_column('firewall_maliciousip', 
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=True)
    )
    op.add_column('firewall_maliciousip', 
        sa.Column('no_of_ports_used', sa.Integer(), nullable=True)
    )
    op.add_column('firewall_maliciousip',
        sa.Column('no_of_victims', sa.Integer(), nullable=True)
    )
    op.alter_column('firewall_maliciousip', 'hits', new_column_name='no_of_hits')
    op.add_column('firewall_affected_device', 
        sa.Column('device_name', sa.String(length=255), nullable=False)
    )

    # rename tables downgrade
    op.rename_table('firewall_maliciousip', 'maliciousip')
    op.rename_table('firewall_affected_device', 'affected_device')
    # ### end Alembic commands ###
