"""Added firewall malicious IPs related tables

Revision ID: 350c66f32786
Revises: be01f1a9f59e
Create Date: 2021-01-12 17:37:53.073250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350c66f32786'
down_revision = 'be01f1a9f59e'
branch_labels = None
depends_on = None


categoryEnum = sa.Enum('DDOS', 'INBOUND', 'OUTBOUND', name='ipcategory')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affected_device',
    sa.Column('ip', sa.String(length=255), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ip', 'device', 'device_name', 'customer_id')
    )
    op.create_table('maliciousip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('ip', sa.String(length=255), nullable=False),
    sa.Column('ip_location', sa.String(length=255), nullable=True),
    sa.Column('category', categoryEnum, nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('no_of_ports_used', sa.Integer(), nullable=True),
    sa.Column('no_of_victims', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ip'),
    sa.UniqueConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maliciousip')
    op.drop_table('affected_device')
    # ### end Alembic commands ###
