"""Added user table.

Revision ID: be01f1a9f59e
Revises: 
Create Date: 2021-04-22 18:05:17.231143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be01f1a9f59e'
down_revision = None
branch_labels = None
depends_on = None


userRolesEnum = sa.Enum('ADMIN', 'USER', name='userroles')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('hashed_password', sa.String(length=255), nullable=True),
        sa.Column('role', userRolesEnum, nullable=True),
        sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    userRolesEnum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
