"""Added browser user role

Revision ID: cf23g1a9g71h
Revises: 1b46d55146b6
Create Date: 2021-06-02 18:05:17.231143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf23g1a9g71h'
down_revision = '1b46d55146b6'
branch_labels = None
depends_on = None

oldUserRolesEnum = sa.Enum('ADMIN', 'USER', name='userroles')
updatedUserRolesEnum = sa.Enum('ADMIN', 'USER', 'BROWSER', name='userroles')
tmp_type = sa.Enum('ADMIN', 'USER', 'BROWSER', name='_tempenum')

tcr = sa.sql.table('users', sa.Column('role', updatedUserRolesEnum, nullable=False))


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a temporary "_tempenum" type, convert and drop the "old" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE users ALTER COLUMN role TYPE _tempenum'
               ' USING role::text::_tempenum')
    oldUserRolesEnum.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the new role enum type
    updatedUserRolesEnum.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE users ALTER COLUMN role TYPE status'
               ' USING role::text::userroles')
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete all users with browser role
    op.execute(tcr.delete().where(tcr.c.role==u''))
    # Create a temporary "_tempenum" type, convert and drop the "new" type
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE users ALTER COLUMN role TYPE _tempenum'
               ' USING role::text::_tempenum')
    updatedUserRolesEnum.drop(op.get_bind(), checkfirst=False)
    # Create and convert to the old role enum type
    oldUserRolesEnum.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE users ALTER COLUMN role TYPE status'
               ' USING role::text::userroles')
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
